//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.DAO
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ClinicalEntities : DbContext
    {
        public ClinicalEntities()
            : base("name=ClinicalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Archetype> Archetypes { get; set; }
        public virtual DbSet<Data> Data1 { get; set; }
        public virtual DbSet<Doctor> Doctors { get; set; }
        public virtual DbSet<Feature> Features { get; set; }
        public virtual DbSet<OperationalsTemplate> OperationalsTemplates { get; set; }
        public virtual DbSet<PatientRecord> PatientRecords { get; set; }
        public virtual DbSet<Patient> Patients { get; set; }
        public virtual DbSet<TemplateAttribute> TemplateAttributes { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<FeatureGroup> FeatureGroups { get; set; }
        public virtual DbSet<RolesGroup> RolesGroups { get; set; }
    }
}
