//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feature
    {
        public int Id { get; set; }
        public string name { get; set; }
        public string Description { get; set; }
        public Nullable<short> DisplayMenu { get; set; }
        public int TemplateId { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public System.DateTime UpdatedAt { get; set; }
        public int UserId { get; set; }
    
        public virtual OperationalsTemplate OperationalsTemplate { get; set; }
        public virtual User User { get; set; }
    }
}
